apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1 # change to 10 or higher for testing autoscaling
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
# outcomment the following lines to test persistent volume claim
#          volumeMounts:
#            - mountPath: "/var/www/html"
#              name: nginx-pv
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
# outcomment the following lines to test persistent volume claim
#      volumes:
#        - name: nginx-pv
#          persistentVolumeClaim:
#            claimName: nginx-pvc